name: test
on:
  pull_request:
  push: { branches: [ main ] }

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
      - name: Run tests
        run: swift test --skip PerformanceTests
